# Generated by Django 2.0.1 on 2018-01-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='imagePath',
            field=models.ImageField(default='No_imange_yet', upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='savePrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='currentPrice',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
