# Generated by Django 2.0.1 on 2018-01-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180121_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='updateTime',
        ),
        migrations.AddField(
            model_name='product',
            name='updateDate',
            field=models.DateField(default='2018-1-20'),
        ),
    ]
